seqCompile: sort.c
	mpicc -o sort sort.c

partACompile: sort_partA.c
	mpicc -o parAsort sort_partA.c

partBcompile: sort_partB.c
	mpicc -o sort_partB sort_partB.c
        
run-seq: seq
	srun -n 1 ./sort 16777216
	srun -n 1 ./sort 33554432
	srun -n 1 ./sort 67108864
	srun -n 1 ./sort 134217728

run-parA: parA
	srun -n 1 ./parAsort 134217728
	srun -n 2 ./parAsort 134217728
	srun -n 4 ./parAsort 134217728
	srun -n 8 ./parAsort 134217728

run-seq: seq
	srun -n 1 ./sort 16777216
	srun -n 1 ./sort 33554432
	srun -n 1 ./sort 67108864
	srun -n 1 ./sort 134217728

run-parB: parB
	srun -n 1 ./sort_partB 16777216
	srun -n 2 ./sort_partB 33554432
	srun -n 4 ./sort_partB 67108864
	srun -n 8 ./sort_partB 134217728